filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log

        include_lines:
          - 'ERROR'
          - 'FATAL'
          - 'CRITICAL'
          - 'Exception'
          - 'authentication failed'
          - 'unauthorized'
          - 'permission denied'
          - 'failed to connect'
          - 'connection refused'
          - 'timeout'
          - 'panic'
          - 'segfault'
          - 'denied'
          - 'failed'
          - 'invalid'
          - '504'
          - '500'

    processors:
      - add_cloud_metadata: ~
      - add_host_metadata: ~
      - add_kubernetes_metadata:
          in_cluster: true
          host: ${NODE_NAME}
          matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    output.logstash:
      hosts: ["logstash-logstash.elk.svc.cluster.local:5044"]

    http:
      enabled: true
      host: 0.0.0.0
      port: 5066


daemonSet:
  livenessProbe:
    httpGet:
      path: /status
      port: 5066
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /status
      port: 5066
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

daemonsetVolumeMounts: []
daemonsetVolumes: []

extraVolumeMounts:
  - mountPath: /var/log/containers
    name: containers-log
    readOnly: true

extraVolumes:
  - hostPath:
      path: /var/log/containers
      type: Directory
    name: containers-log

resources:
  limits:
    cpu: 200m
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 200Mi

elasticsearch:
  enabled: false

kibana:
  enabled: false

secretMounts: []
