apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elk
  labels:
    app: kibana
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: [ "https://elasticsearch-master:9200" ]
    elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
    elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
    elasticsearch.ssl.verificationMode: none
    xpack.security.encryptionKey: "wqfjJcgWiaNMDoxql+pSFDJSRdNTHBNm96jq0ZcpGM="
    xpack.reporting.encryptionKey: "wqfjJcgWiaNMDoxql+pSFDJSRdNTHBNm96jq0ZcpGM="
    xpack.encryptedSavedObjects.encryptionKey: "wqfjJcgWiaNMDoxql+pSFDJSRdNTHBNm96jq0ZcpGM="

